---
openapi: 3.1.0
paths:
  /:
    post:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Post Root
      tags:
      - Invoker
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Root
      tags:
      - Invoker
  /invoker/ws/system/subject-profile/_current:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Current
      tags:
      - Invoker
  /{p1}/{p2}:
    get:
      parameters:
      - name: p1
        in: path
        required: true
        schema:
          type: string
      - name: p2
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Call 2
      tags:
      - Invoker
  /{p1}/{p2}/{p3}:
    get:
      parameters:
      - name: p1
        in: path
        required: true
        schema:
          type: string
      - name: p2
        in: path
        required: true
        schema:
          type: string
      - name: p3
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Call 3
      tags:
      - Invoker
  /{p1}/{p2}/{p3}/{p4}:
    get:
      parameters:
      - name: p1
        in: path
        required: true
        schema:
          type: string
      - name: p2
        in: path
        required: true
        schema:
          type: string
      - name: p3
        in: path
        required: true
        schema:
          type: string
      - name: p4
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Call 4
      tags:
      - Invoker
  /{p1}/{p2}/{p3}/{p4}/{p5}:
    get:
      parameters:
      - name: p1
        in: path
        required: true
        schema:
          type: string
      - name: p2
        in: path
        required: true
        schema:
          type: string
      - name: p3
        in: path
        required: true
        schema:
          type: string
      - name: p4
        in: path
        required: true
        schema:
          type: string
      - name: p5
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Call 5
      tags:
      - Invoker
  /{p1}/{p2}/{p3}/{p4}/{p5}/{p6}:
    get:
      parameters:
      - name: p1
        in: path
        required: true
        schema:
          type: string
      - name: p2
        in: path
        required: true
        schema:
          type: string
      - name: p3
        in: path
        required: true
        schema:
          type: string
      - name: p4
        in: path
        required: true
        schema:
          type: string
      - name: p5
        in: path
        required: true
        schema:
          type: string
      - name: p6
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Call 6
      tags:
      - Invoker
  /{path}:
    post:
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Post Path
      tags:
      - Invoker
    get:
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Get Path
      tags:
      - Invoker
info:
  title: DataSHIELD Invoker API
  version: 1.0.1
  description: Just an example service
  termsOfService: Your terms here
  contact:
    name: Example API Support
    email: techsupport@example.com
    url: http://exampleurl.com/contact
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://localhost:8443
  description: Auto generated value
- url: https://0.0.0.0:8443
  description: Auto generated value
