apiVersion: v1
kind: Pod
metadata:
  name: analysis-responder
  labels:
    app: analysis-responder
spec:
  containers:
  - name: opal
    image: docker.io/datashield/opal_citest:latest
    ports:
    - containerPort: 8443
      hostPort: 8443
    env:
    - name: OPAL_ADMINISTRATOR_PASSWORD
      value: "datashield_test&"
    - name: MONGO_HOST
      value: "mongo"
    - name: MONGO_PORT
      value: "27017"
    - name: MONGO_USER
      value: "root"
    - name: MONGO_PASSWORD
      value: "foobar"
    - name: ROCK_HOSTS
      value: "rock:8085"
    - name: ROCK_ADMINISTRATOR_PASSWORD
      value: "foobar"
  - name: mongo
    image: mongo:4.4.15
    ports:
    - containerPort: 27017
      hostPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "root"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "foobar"
  - name: rock
    image: datashield/rock-margin-idiom-permissive:latest
    ports:
    - containerPort: 8085
      hostPort: 8085
    env:
    - name: DEBUG
      value: "FALSE"
