apiVersion: v1
kind: Pod
metadata:
  name: analysis-requester_pod
  labels:
    app: analysis-requester_pod
spec:
  containers:
  - name: opal_proxy
    image: docker.io/datashield5s/opal-proxy:latest
    ports:
    - containerPort: 8543
      hostPort: 9443
    volumeMounts:
    - name: requester-cert_volume
      mountPath: /data
      readOnly: true
  - name: invoker-webportal
    image: docker.io/datashield5s/invoker-webportal:latest
    ports:
    - containerPort: 80
      hostPort: 8080
  volumes:
  - name: requester-cert_volume
    hostPath:
      path: ./focus5-volume
      type: DirectoryOrCreate
