#
# Copyright (c) 2025, Focus-5 Consortium Members
#

apiVersion: v1
kind: Pod
metadata:
  name: analysis-requester
  labels:
    app: analysis-requester
spec:
  containers:
  - name: opal_proxy
    image: docker.io/datashield5s/opal-proxy:latest
    env:
    - name: OPAL_PROXY_HOST
      valueFrom:
        configMapKeyRef:
          name: analysis-requester_config
          key: requester-opal-proxy_host
    - name: OPAL_PROXY_PORT
      valueFrom:
        configMapKeyRef:
          name: analysis-requester_config
          key: requester-opal-proxy_port
    - name: OPAL_HOST
      valueFrom:
        configMapKeyRef:
          name: analysis-requester_config
          key: responder-opal_host
    - name: OPAL_PORT
      valueFrom:
        configMapKeyRef:
          name: analysis-requester_config
          key: responder-opal_port
    ports:
    - containerPort: 9443
      hostPort: 9443
    volumeMounts:
    - name: requester-cert_volume
      mountPath: /data
      readOnly: true
  - name: requester-webportal
    image: docker.io/datashield5s/invoker-webportal:latest
    ports:
    - containerPort: 80
      hostPort: 8080
  volumes:
  - name: requester-cert_volume
    hostPath:
      path: ./focus5-volume
      type: DirectoryOrCreate
