apiVersion: v1
kind: Pod
metadata:
  name: datashield-invoker
  labels:
    app: datashield-invoker
spec:
  containers:
  - name: datashield-invoker
    image: docker.io/focus5/datashield-invoker:latest
    ports:
      - containerPort: 8443
        hostPort: 8443
