apiVersion: v1
kind: Pod
metadata:
  name: datashield-invoker
  labels:
    app: datashield-invoker
spec:
  containers:
  - name: datashield-invoker
    image: docker.io/focus5/datashield-invoker:latest
    ports:
    - containerPort: 8543
      hostPort: 9443
    volumeMounts:
    - name: focus5-volume
      mountPath: /data
      readOnly: true
  - name: direct-proxy
    image: docker.io/focus5/direct-proxy
    ports:
    - containerPort: 8643
      hostPort: 10443
    volumeMounts:
    - name: focus5-volume
      mountPath: /data
      readOnly: true
  volumes:
  - name: focus5-volume
    hostPath:
      path: ./focus5-volume
      type: DirectoryOrCreate
