#
# Copyright (c) 2023, Focus-5 Consortium Members
#

MAKE = make

all:
	$(MAKE) -C datashield-invoker all

push:
	$(MAKE) -C datashield-invoker push

clean:
	$(MAKE) -C datashield-invoker clean

purge:
	$(MAKE) -C datashield-invoker purge
